---
title: "R Notebook"
output: html_notebook
---
```{r}
#install.packages("twitteR")
#install.packages("tidytext")
#install.packages("dplyr")
#install.packages("ggplot2")
```

```{r}




#package versions : base64enc_0.1-3 httr_1.2.1 twitteR_1.1.8

library(tidyverse)
library(twitteR)
library(rtweet)
library(openssl)
library(httpuv)
library(ROAuth)
library(base64enc)
library("openssl")
library("httpuv")
library("twitteR")
library("tm")
library("stringr")
library("dplyr")
```

```{r}
rtweet_app()

auth_setup_default()

auth <- rtweet_app()

auth_as(auth)

auth_save(auth, "some-name")

#auth_as("some-name")

auth
```

```{r}
app <- rtweet_app(bearer_token = Sys.getenv("RTWEET_BEARER"))
auth_as(app)
```
```{r}

auth_list()

my_authorization <- rtweet::create_token(app = "your app name",
 consumer_key = "your consumer key",
 consumer_secret = "your consumer secret", access_token="your access token", access_secret = "Your access secret")

auth_as("default")
```


```{r}
setup_twitter_oauth("89AVnVNJKUJK9tzJ4k42n0bBe", "lauGldrI9zIGS9Z9trjaaxzkZEZqQerRF2zd5W3EwJFskPjEUN")
```

```{r}
setup_twitter_oauth("rgUgpNvMB8DmkidWhGYJehXI5", "YCbjbRhSDnXCnNtWuJCAFsyKuILEQ5dyHa02m2Wn3pHYiGf7p6")
```


```{r}
API_key = "hBH69ym204DAcm1c6O6fN9jbL" 
API_secret = "rSn5c7XXiewIFcOQzgnbWpKji7mMrN0wP7EbKJt22Niyjx5EW8"
Access_token = "827780929242398720-nfbtSx9t4DltxlhFK6a8vlck42M7gHH"
Access_secret = "bwK2rExYZayCl2p5DuYRbYmhxCjdNRQXwdso98gCsY4Yj"

setup_twitter_oauth(API_key,API_secret,access_token=Access_token,access_secret=Access_secret)

origop <- options("httr_oauth_cache")
options(httr_oauth_cache = TRUE)
```

```{r}
packages <- c("twitteR", "openssl")
### checking if packages are already installed and installing if not
for(i in packages){
    if(!(i %in% installed.packages()[, "Package"])){
        install.packages(i)
    }
library(i, character.only = TRUE) ## load packages
}

setup_twitter_oauth("X2dGQ2lPZllmMjdRNmFSZDJiVm46MTpjaQ", "gNGMQ-lfil3TfyG4guRBdLyggWyzgvs9R5w6VkPH6xmbeEP-R2") 
```

